ABC.exe: main.o big2.o  big3.o  fact.o  fibanaci.o  pallindrome.o  reverse.o  sortingnumbers.o  sumof2numbers.o 
	gcc -o ABC.exe main.o big2.o  big3.o  fact.o  fibanaci.o  pallindrome.o  reverse.o  sortingnumbers.o  sumof2numbers.o

main.o: main.c
	gcc -c main.c

big2.o: big2.c
	gcc -c big2.c
big3.o: big3.c
	gcc -c big3.c
fact.o: fact.c
	gcc -c fact.c
fibanaci.o: fibanaci.c
	gcc -c fibanaci.c
pallindrome.o: pallindrome.c
	gcc -c pallindrome.c
reverse.o: reverse.c
	gcc -c reverse.c
sortingnumbers.o: sortingnumbers.c
	gcc -c sortingnumbers.c 
sumof2numbers.o: sumof2numbers.c
	gcc -c sumof2numbers.c
clean:
	rm -rf *.o
